### PR TITLE
Upgrading cdlib to v0.4.0

### PR DESCRIPTION
**Pull request by GiulioRossetti**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by GiulioRossetti** [comment]
@conda-forge-admin, please rerender

**Review by mediocretech — CHANGES_REQUESTED** [review]
You may just need to update the source sha:
`sha256: 52433dd4f7b980f78498f48dc16029801007c5e1cd0c8ac08e3a40e92c517ab0`

**Comment by GiulioRossetti** [comment]
Where/how can I do it?

**Comment by mediocretech** [comment]
> Where/how can I do it?
https://github.com/GiulioRossetti/cdlib-feedstock/blob/0b707868086fcdebe4f3c8f1be5352a0fcdfc2aa/recipe/meta.yaml#L10

**Comment by mediocretech** [comment]
Looks like the bot beat you to it. 

https://github.com/conda-forge/cdlib-feedstock/pull/2

**Comment by GiulioRossetti** [comment]
> Looks like the bot beat you to it.
> 
> #2

Nice, I just pushed v0.4.0 on pypi yesterday: that's a good bot!

**Pull request closed without merging**
